name: 'On Create Repository'

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  SERVICE_TYPE: 'ecs-tasks'
    
jobs:
  createDevResources:
    if: github.ref_name == 'main'
    uses: cailleach-devops/tfc-shared-actions/.github/workflows/tfc-starter.yml@main
    with:      
      tfc-organization: ${{ vars.TFC_ORGANIZATION }}
      tfc-project-id: ${{ vars.DEV_SPACE_PRJ }}
      git-project: ${{ vars.PROJECT_NAME }}
      environment: 'dev'
    secrets:
      tfc-token: ${{ secrets.TFC_TOKEN }}

  createHmlResources:
    if: github.ref_name == 'main'
    uses: cailleach-devops/tfc-shared-actions/.github/workflows/tfc-starter.yml@main
    with:      
      tfc-organization: ${{ vars.TFC_ORGANIZATION }}
      tfc-project-id: ${{ vars.HML_SPACE_PRJ }}
      git-project: ${{ vars.PROJECT_NAME }}
      environment: 'hml'
    secrets:
      tfc-token: ${{ secrets.TFC_TOKEN }}

  createPrdResources:
    if: github.ref_name == 'main'
    uses: cailleach-devops/tfc-shared-actions/.github/workflows/tfc-starter.yml@main
    with:      
      tfc-organization: ${{ vars.TFC_ORGANIZATION }}
      tfc-project-id: ${{ vars.PRD_SPACE_PRJ }}
      git-project: ${{ vars.PROJECT_NAME }}
      environment: 'prd'
    secrets:
      tfc-token: ${{ secrets.TFC_TOKEN }}
        