name: 'OnPullRequest'

on:  
  pull_request:
    types: [opened, reopened]
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  node-ecs-pull-request:
    uses: cailleach-devops/tfc-shared-actions/.github/workflows/node-ecs-pull-request.yml@main
    with:
      tfc-organization: ${{ vars.TFC_ORGANIZATION }}
    secrets:
      tfc-token: ${{ secrets.TFC_TOKEN }}
