name: 'On User Action'

on:
  workflow_dispatch:
    inputs:
      environments:
        type: environment

permissions:
  contents: read
  id-token: write
  
jobs:
  justOutput:
    runs-on: ubuntu-latest

    steps:
    - name: planOutput
      shell: bash
      run: echo "Estamos aqui  ${var.AWS_ACCOUNT}"